# NumPy Introduction

## What is NumPy?

NumPy stands for Numerical Python. It is a powerful Python library used for scientific computing.  
It provides support for working with large arrays, matrices, and a wide range of mathematical functions.

## Why use NumPy?

- NumPy is faster and more memory-efficient than regular Python lists.
- It allows you to perform operations on entire arrays without writing loops.
- It is used in data analysis, machine learning, deep learning, simulations, image processing, and more.

## Where is NumPy used?

- Data Science and Data Analysis
- Machine Learning and AI
- Scientific Research
- Signal and Image Processing
- Statistical Computing

## Python List vs NumPy Array

| Feature          | Python List         | NumPy Array         |
|------------------|----------------------|----------------------|
| Speed            | Slower               | Faster               |
| Memory           | More memory usage    | Less memory usage    |
| Operations       | Manual loops         | Vectorized           |
| Math Functions   | Not built-in         | Built-in support     |



In [2]:
import numpy as np # Import numpay library (package) to use

In [3]:
np.__version__

'1.26.4'

In [4]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

## Create a list

In [5]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

## List to Array Conversion 

In [7]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr) #N dimention array

numpy.ndarray

## Some of Numpy function

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [11]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### Frist Argument/value must be smaller than second else return empty []

In [14]:
np.arange(20,10)

array([], dtype=int32)

In [15]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [16]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [17]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [18]:
np.zeros(10, dtype=int) #parameter tunning (hyper parameter tunning)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.zeros(10) #parameter tunning 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
print(np.zeros(5,dtype=int))
print(np.zeros(5,dtype=float))
print(np.zeros(5,dtype=bool))
print(np.zeros(5,dtype=complex))

[0 0 0 0 0]
[0. 0. 0. 0. 0.]
[False False False False False]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


In [21]:
np.zeros((2,2,),dtype=int) #zero with 2d

array([[0, 0],
       [0, 0]])

### Left side = row , Right side = Column 

In [22]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
np.zeros((10,10),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
np.ones(6,dtype=int)

array([1, 1, 1, 1, 1, 1])

In [25]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### There is no twos or three function only ones & zeros

In [26]:
np.two((2,3))

AttributeError: module 'numpy' has no attribute 'two'

### By default random.rand it gives value as float

In [27]:
np.random.rand(5)

array([0.6846088 , 0.97501809, 0.36898135, 0.13012996, 0.07861444])

In [28]:
np.random.rand(3) # Every time diffrent value 

array([0.1322339 , 0.90361504, 0.83000177])

In [29]:
np.random.rand(3)  # Every time diffrent value 

array([0.95971909, 0.79454639, 0.53423658])

In [30]:
np.random.randint(4,6) # only print 4 0r 5 not 6

5

### randint function return int value

In [31]:
np.random.randint(2,20,5) 

array([ 4, 13,  6, 17, 10])

In [32]:
np.random.randint(1,2) # Always gives 1

1